### ISSUE TITLE
wireframe checkbox & email

### ISSUE THREAD

**Issue by LainMcGrathTuring** [jordanholtkamp/dev.to#15]

**Comment by CHaiz15** [comment]
Email wireframe:
[wire-dev1.pdf](https://github.com/jordanholtkamp/dev.to/files/4363798/wire-dev1.pdf)
Checkbox wireframe:
[wire-dev2.pdf](https://github.com/jordanholtkamp/dev.to/files/4363799/wire-dev2.pdf)
